### ISSUE TITLE
Not work with Unicode

### ISSUE THREAD

**Issue by qaqland** [vyachkonovalov/bulma-tagsfield#4]
```
😍
你好
高い
``` 
Unicode seems not work. :)

**Comment by crabvk** [comment]
It was made intentionally. AFAIK, there's no support for Unicode matching in JavaScript. But a plugin exists: https://xregexp.com/plugins/
I'd suggest to fork the repo and modify [tagFormat](https://github.com/crabvk/bulma-tagsfield/blob/master/src/tagsfield.js#L3) regex for your needs.

**Comment by qaqland** [comment]
thank you!
